vaadin.launch-browser=true
spring.application.name=vadin-example

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
# Set logging level for your application
logging.level.com.rekreation=DEBUG
logging.level.root=INFO

# Logging pattern for console (can be overridden by logback-spring.xml)
# Uncomment below to test without logback-spring.xml
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n

# Log files location (managed by logback-spring.xml)
logging.file.path=logs